### ISSUE TITLE
Precompiled contracts...

### ISSUE THREAD

**Issue by b00f** [Microsoft/eEVM#11]
Does eEVM support ethereum pre-compiled contracts?

**Comment by flxflx** [comment]
Yes. In fact, it can only run pre-compiled contracts.

**Comment by eddyashton** [comment]
We don't currently implement the precompiled contracts at addresses 1 to 8, as we didn't need them. I'll update the README to make note of this.

If you run bytecode that tries to call one of these contracts, it will throw a notImplemented Exception.

**Comment by b00f** [comment]
Do you have any plan to add pre-compiled contracts or at least providing an option to call pre-compiled contracts from evm (`call` opcode)?

**Comment by eddyashton** [comment]
This isn't a high priority for us, but we'd be happy to take a PR. Given implementations of the precompiled contracts, it should be a small change to the [call opcode handler](https://github.com/Microsoft/eEVM/blob/bb6d7644991913a64cbda56503c834d847e1ccfc/evm/processor.cpp#L1222) to forward a call to a precompiled contract rather than throwing an error.

**Comment by saurik** [comment]
> We don't currently implement the precompiled contracts at addresses 1 to 8, as we didn't need them.

Is there somewhere I can read about the intended use cases for this VM? It just seems strange to me that it is targeting a multi-year old version of the EVM spec (Homestead) and doesn't intend to provide support for basic functionality like ecrecover, so I'm probably misunderstanding what it was made for.
