### ISSUE TITLE
to_json/from_json format suggestion

### ISSUE THREAD

**Issue by unboxedtype** [microsoft/eEVM#40]
Hi! 

I have a suggestion regarding evm::to_json, evm::from_json JSON formatting.
At the moment, to deserialize an Account object from JSON file, you have to provide it in the following format:
```
{
            "address" : "0x100",
            "balance" : "0x100000000000000",
            "nonce"   : 0,
            "code"    : [0]
}
```
All is fine for address and balance, for the nonce I have to provide an integer instead of integer string, and for the code I have to provide array of values.
The last thing looks very inconvenient because most of the tools (solc, web3 console at least?) output code part of an address in a hex string, so we have a compatibility issue here.

What do you think about making the code field a hex-string compatible? I mean, is there any special arguments against it? The same goes for nonce, actually. 

If you don't mind, I would make it on my own producing pull request afterwards.

Thanks!

**Comment by eddyashton** [comment]
Hi,

You're absolutely right - both of these should accept hex strings!

Looks like we got away with this because nothing is actually using the `to_json` conversion for `evm::Account`s. The `parseAccount` function in `tests/harness.cpp` _should_ be using this (its parsing from json in the format you describe, with hex-string nonce and code), but is instead manually converting each field.

There are helpers in `include/util.h` which should be used here: 'to_bytes' and 'to_uint64'.

If you could create a PR fixing this, I'd be very grateful.

Thanks!

**Comment by unboxedtype** [comment]
Yeah, thanks for clarification!

I think the reason you have resorted to manually creating objects in `parseAccount` is that 
EVM tests are formatted in a special way: the address of account is specified in the name of 
the object, while other fields are its attributes.
Have a look (taken from `vmRandomTest.json`)
```
 "pre": {
    "0x0f572e5295c57f15886f9b263e2f6d2d6c7b5ec6": {
       "balance": "0x0de0b6b3a7640000",
       "code": "0x7745414245403745f31387900a8d55",
       "nonce": "0x00",
       "storage": {}
      }
}
```
On the other hand, `evm::from_json(const nlohmann::json& j, Account& a)` expects the JSON object to contain the "address" field. 
In `harness.cpp`, the `parseAddress` function is used exactly for those 'pre' and 'post' objects,
so this makes `evm::from_json` a little bit inappropriate in this setting.

At the moment, I see such options here:
- We can artificially add "address" field to the json object in `parseAddress()`, and then pass it 
into `from_json()`. This may introduce extra copy, because we have `const_iterator` passed into `parseAddress()`.
- Contrary, we can change `from_json` according to described tests format.
- In `harness.cpp`, we can leave things as they are, but nevertheless change `accounts.cpp`. This options does not introduce uniformity, in my opinion.

What do you think?

**Comment by eddyashton** [comment]
Rather than injecting the address field into the json object, I think it would be neater to try to parse the `Account` object from the existing json with all the other fields, and then insert the address from the iterator key. Something like:

```
parseAccount(...)
{
  auto account = it.value().get<Account>();
  account.address = from_hex_str(it.key());
  return {account, j["storage"]};
}
```

The intermediate copy of the `Account` object should be cheap where any json manipulation may not be. `from_json` function will also need to be a little more robust, assigning from "address" (and other keys) _if_ they exist, but simply ignoring them if not present.

**Comment by unboxedtype** [comment]
Yeah, didn't know about `json::get<T>()` function, looks nice.

The only thing I feel sad is that if we construct `Account` using `from_json` but some fields are missing, then we potentially would have undefined values, and we never know that it is so afterwards. I don't have any suggestions regarding this, because, afaik, it is a common thing in C++ programs.

I am thinking about adding a test that will check `to_json`, `from_json` mutual compatibility. For example, initialize `Account` using `from_json`, convert that account into json using `to_json`, and check that both jsons are comparable. What do you think?

**Comment by eddyashton** [comment]
Those fields won't be dangerously undefined - the default constructor for an `Account` will call the default constructor for an `Address`, which will just set the `address` field to 0.

**Comment by unboxedtype** [comment]
Yeah, but is it also true for balance and nonce?
Generally speaking, I would ask myself if it is a good thing to construct
an object without providing all the values at once.
I think, it can backfire if you , for example, serialize a half-initialized
Account object and pass resulting JSON to someone who will deserialize it
later and use it in its own application/logic.

пятница, 9 августа 2019 г. пользователь Eddy Ashton <
notifications@github.com> написал:
> Those fields won't be dangerously undefined - the default constructor for
an Account will call the default constructor for an Address, which will
just set the address field to 0.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci5.googleusercontent.com/proxy/msUn4HmkexZV8aoefq2o3pdZD-RhqBOw4h8oRzYzM9GQnwMcRXcwnllpUFBSADhxu0ixB-K0Qb15t84-PPrfERUCFs9XtX3Ks6h93cYW5zdri5mRtWXflueVS6pA1ILYWCrQ85AmYcEWv-wcrXdfIg2HXbF9PZ6t1AHYgwg9EtMlN_CvO2cN4GIgdB2eT5bYeAWiB8ItTSqYB5r3wnEO-tn3a-AnRTeyHyMUjXJZ4Q=s0-d-e1-ft#https://github.com/notifications/beacon/AIS5XW7LE254WNIHQMI7ZHLQDWSS3A5CNFSM4IKTR5J2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD37JMTY.gif>

**Comment by unboxedtype** [comment]
Sorry, I was unaware of the fact that `uint256_t` relies on `cpp_int ` under the hood, which defaults to zero (C++ is not my native language at the moment).

Still, the `nonce` is left uninitialized when default constructor is used?

**Comment by unboxedtype** [comment]
Should this test pass?
```
TEST_CASE("from_json, to_json tests")                                                                                                    
{                                                                                                                                        
  Account acc1, acc2;                                                                                                                    
  nlohmann::json j;                                                                                                                      
  evm::to_json(j, acc1);                                                                                                                 
  evm::from_json(j, acc2);                                                                                                               
  CHECK(acc1 == acc2);                                                                                                                   
}         
```
As for now, it doesn't because of uninitialized `nonce`.

**Comment by eddyashton** [comment]
We can ensure the nonce (and other fields) is always initialised by setting a default value:

```
struct Account
{
    Address address = {};
    uint64_t nonce = {};
    uint256_t balance = {};
    Code code = {};
```

(This is the same as writing `uint64_t nonce = 0`, but the uniform initializer `{}` should work for _every_ type)

That test should pass, and I believe with the current code it will? `to_json` should always write all 4 values, producing a json object with `address`, `balance`, `nonce`, and `code` fields. `from_json` should convert that json object back to an identical `Account`, but will also accept json objects which are missing those fields.

The `json::get<T>()` function uses argument-dependent lookup to find the `from_json` function for the specified type, but in most cases the same lookup should be done for the assignment operator:

```
Account a1;
nlohmann::json j = a1;
Account a2 = j;
```

So you should never need to call `to_json` or `from_json` directly. (I prefer `auto a2 = j.get<Account>()` because it is explicit, and removes compiler errors in a few places where the assignment would otherwise be ambiguous).

**Comment by unboxedtype** [comment]
Yeah, this looks very C++-11 -ideomatic. Lets discuss further details in the PR.

**Comment by unboxedtype** [comment]
This is now fixed. Closing...
