### ISSUE TITLE
Example of decoding signed TX

### ISSUE THREAD

**Issue by jafri** [microsoft/eEVM#64]
Having some difficulties decoding a signed TX using eEVM, for example:

```
f866808609184e72a0008303000094b0920c523d582040f2bcb1bd7fb1c7c1ecebdb34808025a0e948a3307231941c23f678a0194089fcd52bd62310ee29b7a589e8c60bfec02aa064154144171470510d686559fe3e168f38a4e02c61e7b1aa2f8a19889836534c
```

Are there any examples of this @eddyashton ?

**Comment by jafri** [comment]
I was able to do it like this

```
  std::tuple decodedTx = eevm::rlp::decode<
    uint256_t, uint256_t, uint256_t, vector<uint8_t>, uint256_t, vector<uint8_t>, vector<uint8_t>, vector<uint8_t>, vector<uint8_t>
  >(properTx);
```

Initially I was trying uint256_t instead of the vectors, and it was truncating the result. Let me know if there is a better way to decode :)

**Comment by eddyashton** [comment]
Your sample is close, but I don't think it will correctly decode contract deployment transactions. For these, the `to` field will be _empty_. To handle this I recommend decoding the 4th argument as `std::vector<uint8_t>`, then checking whether its empty. As a quick sketch:

```

struct SignedEthTx
{
  uint256_t nonce;
  uint256_t gas_price;
  uint256_t gas_limit;
  std::optional<eevm::Address> to;
  uint256_t value;
  std::vector<uint8_t> data;
  uint256_t v;
  uint256_t r;
  uint256_t s;
};

SignedEthTx decode_signed_tx(const std::vector<uint8_t>& encoded)
{
  const auto tup = eevm::rlp::decode<
    uint256_t,
    uint256_t,
    uint256_t,
    std::vector<uint8_t>,
    uint256_t,
    std::vector<uint8_t>,
    uint256_t,
    uint256_t,
    uint256_t>(encoded);

  SignedEthTx tx;
  tx.nonce = std::get<0>(tup);
  tx.gas_price = std::get<1>(tup);
  tx.gas_limit = std::get<2>(tup);

  const auto& to_vec = std::get<3>(tup);
  if (to_vec.empty())
  {
    tx.to = std::nullopt;
  }
  else
  {
    tx.to = from_big_endian(to_vec.data(), to_vec.size());
  }

  tx.value = std::get<4>(tup);
  tx.data = std::get<5>(tup);
  tx.v = std::get<6>(tup);
  tx.r = std::get<7>(tup);
  tx.s = std::get<8>(tup);

  return tx;
}
```

2 minor related points from the Yellow Paper:
- it may be sufficient to store v in a `uint8_t` rather than a full 256-bits.
- when encoding transactions, the `to` field should not be treated as a number. It is either an empty list, or exactly 160 bits. If you pass an `eevm::Address` directly to `rlp::encode`, it will be treated as an unsigned number and any leading 0s will be stripped, potentially leaving less than 160 bits.
