### ISSUE TITLE
RLP decoding doesn't throw an error on improper cases

### ISSUE THREAD

**Issue by jafri** [microsoft/eEVM#67]
Here are some RLP strings that are decoded normally although the result is incorrect

1. (empty byte 00)
```
f86103018207d094b94f5374fce5edbc8e2a8697c15331677e6ebf0b0a8255441ca098ff921201554726367d2be8c804a7ff89ccf285ebc57dff8ae4c4400b9c19ac4aa08887321be575c8095f789dd4c743dfe42c1820f9231f98a962b210e3ac2452a3
```

2.
```
0xf86103018207d094b94f5374fce5edbc8e2a8697c15331677e6ebf0b0a8255441ca098ff921201554726367d2be8cef804a7ff89ccf285ebc57dff8ae4c44b9c19ac4aa08887321be575c8095f789dd4c743dfe42c1820f9231f98a962b210e3ac2452a3
```

Can be verified online at https://codechain-io.github.io/rlp-debugger/ (try removing 00 from #1)

**Comment by eddyashton** [comment]
I believe this is just because the RLP decoder doesn't require that it uses every byte presented, is that right?

It will use the first N bytes it needs to decode the requested items, but doesn't protest if extra bytes remain. So given `0x2a`, `0x2a01`, or `0x2aa11bbccadad...` and trying to decode a single `uint`, it will always produce `42`. I believe this is safe, since RLP-encodings describe their own length, but I can add a strict decoding option which will ensure all of the input is consumed.

**Comment by jafri** [comment]
@eddyashton strict should probably be default as it will fail Transaction Tests from https://github.com/ethereum/tests otherwise
